name: Send EgyptAir Emails

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */1 * * *'

jobs:
  send_email:
    name: Send mails
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3.8.0
        with:
            # Specify connection via URL (replaces server_address, server_port, secure,
            # username and password)
            #
            # Format:
            #
            #  * smtp://user:password@server:port
            #  * smtp+starttls://user:password@server:port
            # connection_url: ${{secrets.MAIL_CONNECTION}}
            # Required mail server address if not connection_url:
            server_address: smtp.gmail.com
            # Server port, default 25:
            server_port: 465
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
            # Optional (recommended) mail server username:
            username: ${{secrets.MAIL_USERNAME}}
            # Optional (recommended) mail server password:
            password: ${{secrets.MAIL_PASSWORD}}
            # Required mail subject:
            subject: Mishandled Baggage
            # Required recipients' addresses: wecare@egyptair.com, 
            to: stanleeparker12@gmail.com
            # Required sender full name (address can be skipped):
            from: Stanley Okwii # <user@example.com>
            # Optional plain body:
            # body: "I am writing to bring to your attention an issue regarding my baggage during my recent trip from Entebbe, Uganda, to London, UK on September 16th, 2023. My journey involved a transfer via EgyptAir flight MS838 from Entebbe, Uganda, to Cairo, Egypt, where I had a layover.  And my connecting flight was British Airways flight BA 385. EgyptAir informed me that my baggage would be transferred to my final destination, London. \
            # However, upon reaching the departure gate for BA 385, the British Airways front desk staff informed me that my baggage had not been received from EgyptAir. To my dismay, upon arrival at Heathrow Airport in London, my baggage was nowhere to be found. \
            # This situation has caused significant inconvenience as my baggage contained essential items. I would appreciate it if you could promptly provide me with information about the whereabouts of my luggage. I am willing to cooperate to resolve this matter as soon as possible and trust that you will take the necessary steps to rectify this situation. \
            # For your reference, my flight booking reference is NSM7IL, and my baggage ticket number is 0077 MS 748253. To ensure effective communication, you can reach me via email at stanlee.okwii@gmail.com.
            
            # I eagerly await your prompt response and resolution of this issue.. \
            
            # Sincerely,
            # Stanley Okwii
            # "
            # Optional HTML body read from file:
            html_body: file://Email.html
            # Optional carbon copy recipients:
            # cc: kyloren@example.com,leia@example.com
            # Optional blind carbon copy recipients:
            # bcc: r2d2@example.com,hansolo@example.com
            # Optional recipient of the email response:
            reply_to: stanlee.okwii@gmail.com
            # Optional Message ID this message is replying to:
            # in_reply_to: <random-luke@example.com>
            # Optional unsigned/invalid certificates allowance:
            ignore_cert: true
            # Optional converting Markdown to HTML (set content_type to text/html too):
            convert_markdown: true
            # Optional attachments:
            # attachments: attachments.zip,git.diff,./dist/static/*.js
            # Optional priority: 'high', 'normal' (default) or 'low'
            priority: high
