name: Send emails to EgyptAir

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */1 * * *'

jobs:
  send_email:
    name: Send emails
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3.8.0
        with:
            # Specify connection via URL (replaces server_address, server_port, secure,
            # username and password)
            #
            # Format:
            #
            #  * smtp://user:password@server:port
            #  * smtp+starttls://user:password@server:port
            # connection_url: ${{secrets.MAIL_CONNECTION}}
            # Required mail server address if not connection_url:
            server_address: smtp.gmail.com
            # Server port, default 25:
            server_port: 465
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
            # Optional (recommended) mail server username:
            username: ${{secrets.MAIL_USERNAME}}
            # Optional (recommended) mail server password:
            password: ${{secrets.MAIL_PASSWORD}}
            # Required mail subject:
            subject: Flight Booking NSM7IL
            # Required recipients' addresses: wecare@egyptair.com, 
            to: wecare@egyptair.com
            # Required sender full name (address can be skipped):
            from: Stanley Okwii # <user@example.com>
            # Optional plain body:
            body: "You have mishandled my baggage and refused to take accountability for it. That’s so unprofessional. \n\n
            I handed over my baggage to you and paid for it’s safe delivery. My baggage didn’t arrive at Heathrow as you promised. \n\n
            I eagerly await your prompt response and resolution of this issue \n\n
            Sincerely, \n
            Stanley Okwii \n"
            # Optional HTML body read from file:
            # html_body: file://Email.html
            # Optional carbon copy recipients:
            # cc: stanleeparker12@gmail.com
            # Optional blind carbon copy recipients:
            bcc: mybaggage@egyptair.com, cairo@egyptair.com
            # Optional recipient of the email response:
            reply_to: stanlee.okwii@gmail.com
            # Optional Message ID this message is replying to:
            # in_reply_to: <random-luke@example.com>
            # Optional unsigned/invalid certificates allowance:
            ignore_cert: true
            # Optional converting Markdown to HTML (set content_type to text/html too):
            convert_markdown: true
            # Optional attachments:
            # attachments: attachments.zip,git.diff,./dist/static/*.js
            # Optional priority: 'high', 'normal' (default) or 'low'
            priority: high
